export default {
  "login": "Artash123456",
  "id": 72310488,
  "node_id": "MDQ6VXNlcjcyMzEwNDg4",
  "avatar_url": "https://avatars.githubusercontent.com/u/72310488?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Artash123456",
  "html_url": "https://github.com/Artash123456",
  "followers_url": "https://api.github.com/users/Artash123456/followers",
  "following_url": "https://api.github.com/users/Artash123456/following{/other_user}",
  "gists_url": "https://api.github.com/users/Artash123456/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Artash123456/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Artash123456/subscriptions",
  "organizations_url": "https://api.github.com/users/Artash123456/orgs",
  "repos_url": "https://api.github.com/users/Artash123456/repos",
  "events_url": "https://api.github.com/users/Artash123456/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Artash123456/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Artashes",
  "company": null,
  "blog": "https://mikaelyan.netlify.app/",
  "location": "Armenia, Yerevan",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 5,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2020-10-03T15:07:15Z",
  "updated_at": "2021-04-07T17:28:22Z"
};